services:
  - type: web
    name: catalogue-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn catalogue_web.wsgi --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
