# Generated by Django 5.0.14 on 2026-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_new_product_new_badge_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Katalog.uz', max_length=200)),
                ('telegram_bot_token', models.CharField(default='8747827295:AAFFp9hVKUcnswXoFuQKdiVcqXMRBsrEf_c', max_length=200)),
                ('telegram_group_id', models.CharField(default='-1003987890658', max_length=50)),
                ('telegram_owner_id', models.CharField(default='1077506586', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sozlamalar',
                'verbose_name_plural': 'Sozlamalar',
            },
        ),
    ]
