# Generated by Django 5.0.14 on 2026-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_info',
            field=models.CharField(default="Bog'lanish: info@katalog.uz", max_length=300),
        ),
    ]
