# Generated by Django 5.0.14 on 2026-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_previous_price_sitesettings_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
