# Generated by Django 5.0.14 on 2026-05-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_price_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], unique=True)),
                ('region1', models.CharField(blank=True, max_length=100, null=True, verbose_name='1-xudud')),
                ('region2', models.CharField(blank=True, max_length=100, null=True, verbose_name='2-xudud')),
                ('region3', models.CharField(blank=True, max_length=100, null=True, verbose_name='3-xudud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kunlik jadval',
                'verbose_name_plural': 'Jadval',
                'ordering': ['day_of_week'],
            },
        ),
    ]
